openapi: 3.0.3
info:
  title: Todo App Chat API
  description: API for conversational task management using OpenAI Agents and MCP tools
  version: 1.0.0
servers:
  - url: http://localhost:8000
    description: Development server
paths:
  /api/{user_id}/chat:
    post:
      summary: Send a chat message to the AI assistant
      description: Processes a user message through an AI agent that can interact with task management tools
      parameters:
        - name: user_id
          in: path
          required: true
          description: The ID of the user sending the message
          schema:
            type: string
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ChatRequest'
      responses:
        '200':
          description: Successful response from the AI assistant
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ChatResponse'
        '400':
          description: Bad request - invalid input
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        '401':
          description: Unauthorized - invalid or missing JWT
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        '403':
          description: Forbidden - user trying to access another user's data
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        '500':
          description: Internal server error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
      security:
        - bearerAuth: []
      x-code-samples:
        - lang: javascript
          source: |
            const response = await fetch('/api/user123/chat', {
              method: 'POST',
              headers: {
                'Authorization': 'Bearer YOUR_JWT_TOKEN',
                'Content-Type': 'application/json'
              },
              body: JSON.stringify({
                message: "Add a task to buy groceries"
              })
            });
            const data = await response.json();
            console.log(data);
components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
  schemas:
    ChatRequest:
      type: object
      required:
        - message
      properties:
        message:
          type: string
          description: The user's message to the AI assistant
          example: "Add a task to buy groceries"
        conversation_id:
          type: string
          description: Optional conversation ID to continue an existing conversation. If not provided, a new conversation will be created.
          example: "conv_abc123"
    ChatResponse:
      type: object
      required:
        - conversation_id
        - response
        - tool_calls
      properties:
        conversation_id:
          type: string
          description: The ID of the conversation this response belongs to
          example: "conv_abc123"
        response:
          type: string
          description: The AI assistant's response to the user's message
          example: "I've added the task 'buy groceries' to your list."
        tool_calls:
          type: array
          description: Array of MCP tools called during processing
          items:
            type: object
            properties:
              name:
                type: string
                description: The name of the MCP tool that was called
                example: "add_task"
              arguments:
                type: object
                description: The arguments passed to the MCP tool
                example:
                  user_id: "user123"
                  title: "buy groceries"
                  description: "Need to buy milk, bread, and eggs"
              result:
                type: object
                description: The result returned by the MCP tool
                example:
                  task_id: "task456"
                  status: "created"
    Error:
      type: object
      required:
        - error
        - message
      properties:
        error:
          type: string
          description: Error code
          example: "INVALID_INPUT"
        message:
          type: string
          description: Human-readable error message
          example: "Message field is required"